# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{query_string_parser}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["dan sinclair"]
  s.date = %q{2010-06-15}
  s.description = %q{Simple query string parser}
  s.email = %q{dj2@everburning.com}
  s.extensions = ["ext/extconf.rb", "ext/extconf.rb"]
  s.files = [
    "Rakefile",
     "ext/extconf.rb",
     "ext/pr_query_parser.c",
     "lib/query_string_parser.rb",
     "spec/query_string_parser_spec.rb"
  ]
  s.homepage = %q{http://github.com/dj2/query_string_parser}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Simple query string parser}
  s.test_files = [
    "spec/query_string_parser_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

